[project]
name = "ai-eng-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"


requires-python = ">=3.12,<3.13"
dependencies = [
    "ipykernel>=7.3.0",
    "jupyterlab>=4.6.2",
    "line-profiler>=5.0.2",
    "matplotlib>=3.11.0",
    "memory-profiler>=0.61.0",
    "mlflow>=3",
    "mlxtend>=0.25.0",
    "numpy>=2.5.1",
    "pandas>=2.2,<3",
    "protobuf==3.20.3",
    "scikit-learn>=1.9.0",
    "scipy>=1.18.0",
    "wandb>=0.25.0",
]
